export const metadata = {
  title: "WordPress Banner Embed Guide",
  description: "How to add the SEO Lab seasonal banner to WordPress",
};

export default function WPBannerGuide() {
  return (
    <main className="prose prose-neutral max-w-3xl p-6">
      <h1>WordPress — Add a Seasonal Site Banner (Copy/Paste)</h1>
      <p>
        Use this guide to add the promo banner generated by the Offers Orchestrator to a WordPress site in under 2 minutes.
      </p>
      <h2>What you’ll need</h2>
      <ul>
        <li>The banner embed code from SEO Lab → Apps → Offers Orchestrator</li>
        <li>WordPress access with permission to edit pages or your header template</li>
      </ul>
      <h2>Option A: Add to the Homepage (Block Editor)</h2>
      <ol>
        <li>Open Pages → Home (Edit).</li>
        <li>Click the "+" button and add a "Custom HTML" block at the very top of the page content.</li>
        <li>Paste the banner code from SEO Lab into the HTML block.</li>
        <li>Update/Publish.</li>
      </ol>
      <p>Tip: The banner uses "position: sticky; top: 0" so it stays visible at the top as you scroll.</p>
      <h2>Option B: Add to the Site Header (Reusable/Global)</h2>
      <ol>
        <li>Appearance → Editor (Site Editor).</li>
        <li>Open the Header template (or a template part that’s used site‑wide).</li>
        <li>Add a "Custom HTML" block at the top of the header structure (above the navigation if you want it highest).</li>
        <li>Paste the banner code.</li>
        <li>Save changes.</li>
      </ol>
      <h2>Remove/Replace the Banner</h2>
      <ul>
        <li>To end a promo, delete the HTML block or replace it with a new banner code for the next offer.</li>
        <li>The button link uses the UTM tracking link from SEO Lab, so analytics will show which promo drove bookings.</li>
      </ul>
      <h2>Accessibility & Design Notes</h2>
      <ul>
        <li>The banner has high contrast (white text on dark background) and a clear call‑to‑action button.</li>
        <li>You can edit the background color (#111) and button color (#22c55e) in the inline styles if you want to match your theme.</li>
        <li>Keep banner text short and specific (e.g., "15% off Skin Fades — Book now").</li>
      </ul>
      <p>If you need help placing the banner in your theme, send a note to support and we’ll assist.</p>
    </main>
  );
}
